INSERT INTO `routes` (`number`, `name`) VALUES ('1','Indiana-Hyde Park');
INSERT INTO `routes` (`number`, `name`) VALUES ('2','Hyde Park Express');
INSERT INTO `routes` (`number`, `name`) VALUES ('3','King Drive');
INSERT INTO `routes` (`number`, `name`) VALUES ('4','Cottage Grove');
INSERT INTO `routes` (`number`, `name`) VALUES ('N5','South Shore Night Bus');
INSERT INTO `routes` (`number`, `name`) VALUES ('6','Jackson Park Express');
INSERT INTO `routes` (`number`, `name`) VALUES ('7','Harrison');
INSERT INTO `routes` (`number`, `name`) VALUES ('8','Halsted');
INSERT INTO `routes` (`number`, `name`) VALUES ('8A','South Halsted');
INSERT INTO `routes` (`number`, `name`) VALUES ('9','Ashland');
INSERT INTO `routes` (`number`, `name`) VALUES ('10','Museum of Science &amp; Industry');
INSERT INTO `routes` (`number`, `name`) VALUES ('11','Lincoln/Sedgwick');
INSERT INTO `routes` (`number`, `name`) VALUES ('12','Roosevelt');
INSERT INTO `routes` (`number`, `name`) VALUES ('14','Jeffery Express');
INSERT INTO `routes` (`number`, `name`) VALUES ('15','Jeffery Local');
INSERT INTO `routes` (`number`, `name`) VALUES ('17','Westchester');
INSERT INTO `routes` (`number`, `name`) VALUES ('18','16th-18th');
INSERT INTO `routes` (`number`, `name`) VALUES ('19','United Center Express');
INSERT INTO `routes` (`number`, `name`) VALUES ('20','Madison');
INSERT INTO `routes` (`number`, `name`) VALUES ('21','Cermak');
INSERT INTO `routes` (`number`, `name`) VALUES ('22','Clark');
INSERT INTO `routes` (`number`, `name`) VALUES ('24','Wentworth');
INSERT INTO `routes` (`number`, `name`) VALUES ('26','South Shore Express');
INSERT INTO `routes` (`number`, `name`) VALUES ('28','Stony Island Local');
INSERT INTO `routes` (`number`, `name`) VALUES ('X28','Stony Island Express');
INSERT INTO `routes` (`number`, `name`) VALUES ('29','State');
INSERT INTO `routes` (`number`, `name`) VALUES ('30','South Chicago');
INSERT INTO `routes` (`number`, `name`) VALUES ('33','Mag Mile Express');
INSERT INTO `routes` (`number`, `name`) VALUES ('34','South Michigan');
INSERT INTO `routes` (`number`, `name`) VALUES ('35','35th');
INSERT INTO `routes` (`number`, `name`) VALUES ('36','Broadway');
INSERT INTO `routes` (`number`, `name`) VALUES ('39','Pershing');
INSERT INTO `routes` (`number`, `name`) VALUES ('43','43rd');
INSERT INTO `routes` (`number`, `name`) VALUES ('44','Wallace-Racine');
INSERT INTO `routes` (`number`, `name`) VALUES ('47','47th');
INSERT INTO `routes` (`number`, `name`) VALUES ('48','South Damen');
INSERT INTO `routes` (`number`, `name`) VALUES ('49','Western');
INSERT INTO `routes` (`number`, `name`) VALUES ('49A','South Western');
INSERT INTO `routes` (`number`, `name`) VALUES ('49B','North Western');
INSERT INTO `routes` (`number`, `name`) VALUES ('50','Damen');
INSERT INTO `routes` (`number`, `name`) VALUES ('51','51st');
INSERT INTO `routes` (`number`, `name`) VALUES ('52','Kedzie/California');
INSERT INTO `routes` (`number`, `name`) VALUES ('52A','South Kedzie');
INSERT INTO `routes` (`number`, `name`) VALUES ('53','Pulaski');
INSERT INTO `routes` (`number`, `name`) VALUES ('53A','South Pulaski');
INSERT INTO `routes` (`number`, `name`) VALUES ('54','Cicero');
INSERT INTO `routes` (`number`, `name`) VALUES ('54A','North Cicero/Skokie Blvd.');
INSERT INTO `routes` (`number`, `name`) VALUES ('54B','South Cicero');
INSERT INTO `routes` (`number`, `name`) VALUES ('55','Garfield');
INSERT INTO `routes` (`number`, `name`) VALUES ('55A','55th/Austin');
INSERT INTO `routes` (`number`, `name`) VALUES ('55N','55th/Narragansett');
INSERT INTO `routes` (`number`, `name`) VALUES ('56','Milwaukee');
INSERT INTO `routes` (`number`, `name`) VALUES ('56A','North Milwaukee');
INSERT INTO `routes` (`number`, `name`) VALUES ('57','Laramie');
INSERT INTO `routes` (`number`, `name`) VALUES ('59','59th/61st');
INSERT INTO `routes` (`number`, `name`) VALUES ('60','Blue Island/26th');
INSERT INTO `routes` (`number`, `name`) VALUES ('62','Archer');
INSERT INTO `routes` (`number`, `name`) VALUES ('62H','Archer/Harlem');
INSERT INTO `routes` (`number`, `name`) VALUES ('63','63rd');
INSERT INTO `routes` (`number`, `name`) VALUES ('63W','West 63rd');
INSERT INTO `routes` (`number`, `name`) VALUES ('64','Foster-Canfield');
INSERT INTO `routes` (`number`, `name`) VALUES ('65','Grand');
INSERT INTO `routes` (`number`, `name`) VALUES ('66','Chicago');
INSERT INTO `routes` (`number`, `name`) VALUES ('67','67th-69th-71st');
INSERT INTO `routes` (`number`, `name`) VALUES ('68','Northwest Highway');
INSERT INTO `routes` (`number`, `name`) VALUES ('69','Cumberland/East River');
INSERT INTO `routes` (`number`, `name`) VALUES ('70','Division');
INSERT INTO `routes` (`number`, `name`) VALUES ('71','71st/South Shore');
INSERT INTO `routes` (`number`, `name`) VALUES ('72','North');
INSERT INTO `routes` (`number`, `name`) VALUES ('73','Armitage');
INSERT INTO `routes` (`number`, `name`) VALUES ('74','Fullerton');
INSERT INTO `routes` (`number`, `name`) VALUES ('75','74th-75th');
INSERT INTO `routes` (`number`, `name`) VALUES ('76','Diversey');
INSERT INTO `routes` (`number`, `name`) VALUES ('77','Belmont');
INSERT INTO `routes` (`number`, `name`) VALUES ('78','Montrose');
INSERT INTO `routes` (`number`, `name`) VALUES ('79','79th');
INSERT INTO `routes` (`number`, `name`) VALUES ('80','Irving Park');
INSERT INTO `routes` (`number`, `name`) VALUES ('81','Lawrence');
INSERT INTO `routes` (`number`, `name`) VALUES ('81W','West Lawrence');
INSERT INTO `routes` (`number`, `name`) VALUES ('82','Kimball-Homan');
INSERT INTO `routes` (`number`, `name`) VALUES ('84','Peterson');
INSERT INTO `routes` (`number`, `name`) VALUES ('85','Central');
INSERT INTO `routes` (`number`, `name`) VALUES ('85A','North Central');
INSERT INTO `routes` (`number`, `name`) VALUES ('86','Narragansett/Ridgeland');
INSERT INTO `routes` (`number`, `name`) VALUES ('87','87th');
INSERT INTO `routes` (`number`, `name`) VALUES ('88','Higgins');
INSERT INTO `routes` (`number`, `name`) VALUES ('90','Harlem');
INSERT INTO `routes` (`number`, `name`) VALUES ('90N','North Harlem');
INSERT INTO `routes` (`number`, `name`) VALUES ('91','Austin');
INSERT INTO `routes` (`number`, `name`) VALUES ('92','Foster');
INSERT INTO `routes` (`number`, `name`) VALUES ('93','California/Dodge');
INSERT INTO `routes` (`number`, `name`) VALUES ('94','South California');
INSERT INTO `routes` (`number`, `name`) VALUES ('95W','West 95th');
INSERT INTO `routes` (`number`, `name`) VALUES ('95E','93rd-95th');
INSERT INTO `routes` (`number`, `name`) VALUES ('96','Lunt');
INSERT INTO `routes` (`number`, `name`) VALUES ('97','Skokie');
INSERT INTO `routes` (`number`, `name`) VALUES ('X98','Avon Express');
INSERT INTO `routes` (`number`, `name`) VALUES ('100','Jeffery Manor Express');
INSERT INTO `routes` (`number`, `name`) VALUES ('103','West 103rd');
INSERT INTO `routes` (`number`, `name`) VALUES ('106','East 103rd');
INSERT INTO `routes` (`number`, `name`) VALUES ('108','Halsted/95th');
INSERT INTO `routes` (`number`, `name`) VALUES ('111','Pullman/111th/115th');
INSERT INTO `routes` (`number`, `name`) VALUES ('112','Vincennes/111th');
INSERT INTO `routes` (`number`, `name`) VALUES ('119','Michigan/119th');
INSERT INTO `routes` (`number`, `name`) VALUES ('120','Ogilvie/Wacker Express');
INSERT INTO `routes` (`number`, `name`) VALUES ('121','Union/Wacker Express');
INSERT INTO `routes` (`number`, `name`) VALUES ('122','Illinois Center/Ogilvie Express');
INSERT INTO `routes` (`number`, `name`) VALUES ('123','Illinois Center/Union Express');
INSERT INTO `routes` (`number`, `name`) VALUES ('124','Navy Pier');
INSERT INTO `routes` (`number`, `name`) VALUES ('125','Water Tower Express');
INSERT INTO `routes` (`number`, `name`) VALUES ('126','Jackson');
INSERT INTO `routes` (`number`, `name`) VALUES ('128','Soldier Field Express');
INSERT INTO `routes` (`number`, `name`) VALUES ('129','West Loop/South Loop');
INSERT INTO `routes` (`number`, `name`) VALUES ('130','Museum Campus');
INSERT INTO `routes` (`number`, `name`) VALUES ('132','Goose Island Express');
INSERT INTO `routes` (`number`, `name`) VALUES ('134','Stockton/LaSalle Express');
INSERT INTO `routes` (`number`, `name`) VALUES ('135','Clarendon/LaSalle Express');
INSERT INTO `routes` (`number`, `name`) VALUES ('136','Sheridan/LaSalle Express');
INSERT INTO `routes` (`number`, `name`) VALUES ('143','Stockton/Michigan Express');
INSERT INTO `routes` (`number`, `name`) VALUES ('144','Marine/Michigan Express');
INSERT INTO `routes` (`number`, `name`) VALUES ('145','Wilson/Michigan Express');
INSERT INTO `routes` (`number`, `name`) VALUES ('146','Inner Drive/Michigan Exp.');
INSERT INTO `routes` (`number`, `name`) VALUES ('147','Outer Drive Express');
INSERT INTO `routes` (`number`, `name`) VALUES ('148','Clarendon Michigan Express');
INSERT INTO `routes` (`number`, `name`) VALUES ('151','Sheridan');
INSERT INTO `routes` (`number`, `name`) VALUES ('152','Addison');
INSERT INTO `routes` (`number`, `name`) VALUES ('154','Wrigley Field Express');
INSERT INTO `routes` (`number`, `name`) VALUES ('155','Devon');
INSERT INTO `routes` (`number`, `name`) VALUES ('156','LaSalle');
INSERT INTO `routes` (`number`, `name`) VALUES ('157','Streeterville/Taylor');
INSERT INTO `routes` (`number`, `name`) VALUES ('165','West 65th');
INSERT INTO `routes` (`number`, `name`) VALUES ('169','69th-UPS Express');
INSERT INTO `routes` (`number`, `name`) VALUES ('170','U. of Chicago/Midway');
INSERT INTO `routes` (`number`, `name`) VALUES ('171','U. of Chicago/Hyde Park');
INSERT INTO `routes` (`number`, `name`) VALUES ('172','U. of Chicago/Kenwood');
INSERT INTO `routes` (`number`, `name`) VALUES ('192','U. of Chicago Hospitals Express');
INSERT INTO `routes` (`number`, `name`) VALUES ('201','Central/Ridge');
INSERT INTO `routes` (`number`, `name`) VALUES ('N201','Central/Sherman (Night Bus)');
INSERT INTO `routes` (`number`, `name`) VALUES ('205','Chicago/Golf');
INSERT INTO `routes` (`number`, `name`) VALUES ('206','Evanston Circulator');